version: "3.0"

services:
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - 8081:80
        links:
            - fpm
        volumes:
            - ./:/var/www/Olibrary
    fpm:
        build:
            context: .
            dockerfile: docker/fpm/Dockerfile
        volumes:
            - ./:/var/www/Olibrary
        links:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-33061}:3306'
        environment:
                MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
                MYSQL_DATABASE: '${DB_DATABASE}'
                MYSQL_USER: '${DB_USERNAME}'
                MYSQL_PASSWORD: '${DB_PASSWORD}'
                MYSQL_ALLOW_EMPTY_PASSWORD: 1
